[package]
name = "boxball-rs"
version = "0.0.1"
authors = ["David Roher <david.roher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4" }
strum = "0.19.2"
strum_macros = "0.19.2"
serde = { version = "1.0.115", features = ["derive"] }
csv = "1.1.3"
anyhow = "1.0.32"
regex = "1.3.9"
num-traits = "0.2.12"
smallvec = "1.4.2"
arrayref = "0.3.6"
either = "1.6.0"
lazy_static = "1.4.0"