[package]
name = "boxball-rs"
version = "0.0.1"
authors = ["David Roher <david.roher@gmail.com>"]
edition = "2021"
description = "Creates structured datasets from raw Retrosheet files."
license = "BSL-1.0"
repository = "https://github.com/droher/boxball-rs"
readme = "README.md"
keywords = ["retrosheet", "baseball"]
categories = ["command-line-utilities", "data-processing", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.23", default-features = false, features = ["std", "clock", "serde"]}
strum = "0.24.1"
strum_macros = "0.24.3"
csv = "1.1.6"
anyhow = "1.0.68"
num-traits = "0.2.15"
arrayref = "0.3.6"
arrayvec = {version = "0.7.2", features = ["serde"]}
lazy_static = "1.4.0"
const_format = "0.2.30"
either = {version = "1.8.0", features = ["serde", "use_std"]}
num_enum = "0.5.7"
bimap = "0.6.2"
structopt = "0.3.26"
itertools = "0.10.5"
serde = {version = "1.0.152",  features = ["derive", "rc"]}
serde_json = {version = "1.0.91", features = ["preserve_order"]}
glob = "0.3.1"
rayon = "1.6.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.15"
bounded-integer = {version = "0.5.3", features = ["types", "serde"]}
serde_repr = "0.1.9"
regex = {version = "1.7.1", default-features = false, features = ["std", "perf"]} # No need for unicode
quick_cache = "0.2.0"
fixed-map = "0.8.1"
