[package]
name = "boxball-rs"
version = "0.0.1"
authors = ["David Roher <david.roher@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"]}
strum = "0.23.0"
strum_macros = "0.23.1"
csv = "1.1.6"
anyhow = "1.0.48"
num-traits = "0.2.14"
arrayref = "0.3.6"
lazy_static = "1.4.0"
const_format = "0.2.22"
either = "1.6.1"
num_enum = "0.5.4"
tinystr = {version = "0.4.12", features = ["serde"]}
bimap = "0.6.1"
arrayvec = "0.7.2"
structopt = "0.3.25"
itertools = "0.10.1"
serde = {version = "1.0.130",  features = ["derive"]}
serde_json = "1.0.71"
glob = "0.3.0"
rayon = "1.5.1"

[dependencies.regex]
version = "1.5.4"
# No need for unicode
default-features = false
features = ["std", "perf"]

[profile.release]
lto = "fat"