[package]
name = "boxball-rs"
version = "0.0.1"
authors = ["David Roher <david.roher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"]}
strum = "0.21.0"
strum_macros = "0.21.1"
csv = "1.1.6"
anyhow = "1.0.41"
num-traits = "0.2.14"
arrayref = "0.3.6"
lazy_static = "1.4.0"
const_format = "0.2.14"
either = "1.6.1"
num_enum = "0.5.1"
tinystr = {version = "0.4.7", features = ["serde"]}
bimap = "0.6.1"
arrayvec = "0.7.1"
structopt = "0.3.21"
itertools = "0.10.1"
serde = {version = "1.0.126",  features = ["derive"]}
serde_json = "1.0.64"

[dependencies.regex]
version = "1.4.2"
# No need for unicode
default-features = false
features = ["std", "perf"]

[profile.release]
codegen-units = 1
lto = "fat"