[package]
name = "boxball-rs"
version = "0.0.1"
authors = ["David Roher <david.roher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19" }
strum = "0.20.0"
strum_macros = "0.20.1"
csv = "1.1.5"
anyhow = "1.0.34"
num-traits = "0.2.14"
arrayref = "0.3.6"
lazy_static = "1.4.0"
const_format = "0.2.10"
either = "1.6.1"
num_enum = "0.5.1"
tinystr = "0.4.1"
bimap = "0.5.3"
arrayvec = "0.5.2"

[dependencies.regex]
version = "1.4.2"
# No need for unicode
default-features = false
features = ["std", "perf"]

[profile.release]
lto = true