[package]
name = "boxball-rs"
version = "0.0.1"
authors = ["David Roher <david.roher@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.22", features = ["serde"]}
strum = "0.24.1"
strum_macros = "0.24.3"
csv = "1.1.6"
anyhow = "1.0.61"
num-traits = "0.2.15"
arrayref = "0.3.6"
lazy_static = "1.4.0"
const_format = "0.2.26"
either = {version = "1.7.0", features = ["serde", "use_std"]}
num_enum = "0.5.7"
tinystr = {version = "0.4.12", features = ["serde"]}
bimap = "0.6.2"
structopt = "0.3.26"
itertools = "0.10.3"
serde = {version = "1.0.143",  features = ["derive"]}
serde_json = {version = "1.0.83", features = ["preserve_order"]}
glob = "0.3.0"
rayon = "1.5.3"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
bounded-integer = {version = "0.5.2", features = ["types", "serde"]}
serde_repr = "0.1.9"

[dependencies.regex]
version = "1.6.0"
# No need for unicode
default-features = false
features = ["std", "perf"]
