name: build_parser
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release

      - uses: actions/upload-artifact@v2.2.4
        name: bin
        with:
          path: target/release/boxball-rs

  retrosheet:
    name: retrosheet
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - id: sha
        run: echo "::set-output name=sha::$(git ls-remote https://github.com/droher/retrosheet master)"

      - uses: actions/cache@v3
        id: cache
        with:
          path: retrosheet/
          key: retrosheet-${{ steps.sha.outputs.sha }}

      - if: steps.cache.outputs.cache-hit != 'true'
        run: wget https://github.com/droher/retrosheet/archive/master.zip -O retrosheet.zip
      - if: steps.cache.outputs.cache-hit != 'true'
        run: unzip retrosheet.zip && mv retrosheet-* retrosheet

  run:
    name: run
    needs: [build, retrosheet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: retrosheet/
          key: retrosheet-${{ needs.retrosheet.outputs.sha }}
      - uses: actions/download-artifact@v3
      - run: ls -R