name: build_parser
on: [push]
jobs:
  build:
    name: boxball-rs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release

  retrosheet:
    name: retrosheet
    runs-on: ubuntu-latest
    steps:
      - id: sha
        run: echo "::set-output name=sha::$(git ls-remote https://github.com/droher/retrosheet master)"

      - uses: actions/cache@v3
        with:
          path: |
            retrosheet/
          key: retrosheet-${{ steps.sha.outputs.sha }}

      - run: wget https://github.com/droher/retrosheet/archive/master.zip -O retrosheet.zip
      - run: unzip retrosheet.zip && mv retrosheet-* retrosheet
